stage_5 - added function for save changes in file after user's right answers, added functionality for users answers
Wonderfull23/LearnEnglishWordsTelegramBot pull request #5
Opened 2023-02-07 23:02 UTC by Wonderfull23

2023-02-09 21:46 UTC, ievetrov requested changes
основная проблема – отгадать слово можно только один раз. далее программа вновь показывает главное меню. это не совсем юзерфрендли. 

предлагаю запускать еще цикл, чтобы при правильном и неправильном варианте ответа объявлять результат и продолжать изучение слов. также стоит добавить помимо 4х слов для отгадывания еще "0". для выхода в меню

+ комментарии по коду

2023-02-09 21:46 UTC, ievetrov commented on src/main/kotlin/additional/File.kt
>              else -> println("Неверно введенный номер пукта")
опечатка

2023-02-09 21:46 UTC, ievetrov commented on src/main/kotlin/additional/File.kt
> +                    "0" -> break
when излишен если всего два условия. if else выглядит аккуратнее

2023-02-09 21:46 UTC, ievetrov commented on src/main/kotlin/additional/File.kt
> +            "2" -> statistics(dictionary, learnTimes)
неочевидный нейминг функции. не отвечает на вопрос "что сделать"
более подходящее getStatistics

2023-02-11 16:59 UTC, Wonderfull23 commented on src/main/kotlin/additional/File.kt
> +                    "0" -> break
Там 3 варианта ответа: 0, правильный вариант, else (под else представил как неправильные варианты от 1 до 4, так и рандомные символы)

2023-02-13 07:24 UTC, ievetrov approved these changes
Отлично, а теперь к рефакторингу)

2023-02-13 19:04 UTC, merged