stage_6 refactor code
Wonderfull23/LearnEnglishWordsTelegramBot pull request #6
Opened 2023-02-13 22:38 UTC by Wonderfull23

2023-02-13 22:39 UTC, Wonderfull23 commented
Нужно ли было приводить код в полное соответствие с кодом на виде или нет?

2023-02-15 21:01 UTC, ievetrov requested changes
Нашлась бага

2023-02-15 21:01 UTC, ievetrov commented on src/main/kotlin/additional/File.kt
> +                    if (trainer.checkAnswer(question, userInput)) println("Правильно!")
вот тут дважды вызывается `trainer.checkAnswer`
слова будут учиться в 2 раза быстрее...

2023-02-15 21:02 UTC, ievetrov commented
> Нужно ли было приводить код в полное соответствие с кодом на виде или нет?

нет, это только для ориентира

2023-02-16 21:12 UTC, merged